### ISSUE TITLE
[flutter_todos] flutter get packages fail.

### ISSUE THREAD

**Issue by nosmirck** [felangel/bloc#151]
**Describe the bug**
Following the tutorial for flutter_todos I get the error:
```
[flutter_todos] flutter packages get
Running "flutter packages get" in flutter_todos...              
Error on line 11, column 11: Invalid description in the "todos_repository_simple" pubspec on the "todos_repository_core" dependency: "../todos_repository_core" is a relative path, but this isn't a local pubspec.

   ╷

11 │     path: ../todos_repository_core

   │           ^^^^^^^^^^^^^^^^^^^^^^^^

   ╵
pub get failed (65)
exit code 65
```

**To Reproduce**
1. Create a new project `flutter create flutter_todos`
2. Change the content of `pubspec.yml` to the following:
```
name: flutter_todos
description: A new Flutter project.

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ">=1.1.0 <2.0.0"
  equatable: ^0.2.0
  flutter_bloc: ^0.7.0
  flutter:
    sdk: flutter

dependency_overrides:
  todos_app_core:
    git:
      url: git://github.com/brianegan/flutter_architecture_samples
      path: todos_app_core
  todos_repository_core:
    git:
      url: git://github.com/brianegan/flutter_architecture_samples
      path: todos_repository_core
  todos_repository_simple:
    git:
      url: git://github.com/brianegan/flutter_architecture_samples
      path: todos_repository_simple

flutter:
  uses-material-design: true
```
3. run `flutter packages get`

**Expected behavior**
Get all packages with no errors

**Logs **
flutter analyze output:
```
PS C:\Repos\bloc\examples\flutter_todos> flutter analyze
Error on line 11, column 11: Invalid description in the "todos_repository_simple" pubspec on the "todos_repository_core" dependency: "../todos_repository_core" is a relative path, but this isn't a local pubspec.
   ╷
11 │     path: ../todos_repository_core
   │           ^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
Running "flutter packages get" in flutter_todos...
pub get failed (65)
```

flutter doctor output:
```
PS C:\Repos\bloc\examples\flutter_todos> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.3.11-pre.40, on Microsoft Windows [Version 10.0.17763.379], locale en-CA)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code
[√] VS Code, 64-bit edition (version 1.32.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
PS C:\Repos\bloc\examples\flutter_todos>
```

**Comment by felangel** [comment]
@nosmirck thanks for opening this issue!

Can you please try with the following `pubspec.yaml`:

```yaml
name: flutter_todos
description: A new Flutter project.

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ">=1.1.0 <2.0.0"
  equatable: ^0.2.0
  flutter_bloc: ^0.7.0
  flutter:
    sdk: flutter

dependency_overrides:
  todos_app_core:
    git:
      url: https://github.com/brianegan/flutter_architecture_samples
      path: todos_app_core
  todos_repository_core:
    git:
      url: https://github.com/brianegan/flutter_architecture_samples
      path: todos_repository_core
  todos_repository_simple:
    git:
      url: https://github.com/brianegan/flutter_architecture_samples
      path: todos_repository_simple

flutter:
  uses-material-design: true
```

Thanks! 👍

**Comment by nosmirck** [comment]
Thanks for the fast response @felangel 
I'm getting the same issue with new pubspec content:

```
[flutter_todos] flutter packages get
Running "flutter packages get" in flutter_todos...              
Error on line 11, column 11: Invalid description in the "todos_repository_simple" pubspec on the "todos_repository_core" dependency: "../todos_repository_core" is a relative path, but this isn't a local pubspec.

   ╷

11 │     path: ../todos_repository_core


   │           ^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
pub get failed (65)
exit code 65
```

**Comment by nosmirck** [comment]
I just tried cloning the whole `bloc` repo, navigated to `examples/flutter_todos` and tried `flutter packages get` and I got the same error.

**Comment by felangel** [comment]
@nosmirck oops that's my fault! Just pushed a fix for this. The following `pubspec.yaml` should work:

```yaml
name: flutter_todos
description: A new Flutter project.

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ">=1.1.0 <2.0.0"
  equatable: ^0.2.0
  flutter_bloc: ^0.7.0
  flutter:
    sdk: flutter

dependency_overrides:
  todos_app_core:
    git:
      url: https://github.com/brianegan/flutter_architecture_samples
      path: todos_app_core
      ref: 0d047565ea5bf28c2b2cbdd7a7d9a9d14fff6945
  todos_repository_core:
    git:
      url: https://github.com/brianegan/flutter_architecture_samples
      path: todos_repository_core
      ref: 0d047565ea5bf28c2b2cbdd7a7d9a9d14fff6945
  todos_repository_simple:
    git:
      url: https://github.com/brianegan/flutter_architecture_samples
      path: todos_repository_simple
      ref: 0d047565ea5bf28c2b2cbdd7a7d9a9d14fff6945
flutter:
  uses-material-design: true
```

**Comment by nosmirck** [comment]
@felangel same error.

I believe the problem is here:

https://github.com/brianegan/flutter_architecture_samples/blob/master/todos_repository_simple/pubspec.yaml

The reference for todos_repository_core on line 11 is a relative path.

**Comment by felangel** [comment]
@nosmirck did you try the latest `pubspec.yaml`?

**Comment by nosmirck** [comment]
Yes I did.
```
PS C:\Repos\flutter_todos> flutter packages get
Error on line 11, column 11: Invalid description in the "todos_repository_simple" pubspec on the "todos_repository_core" dependency: "../todos_repository_core" is a relative path, but this isn't a local pubspec.
   ╷
11 │     path: ../todos_repository_core
   │           ^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
Running "flutter packages get" in flutter_todos...
pub get failed (65)
```

**Comment by felangel** [comment]
@nosmirck did you delete your `pubspec.lock`?

I just created a clean project and tested it and it seems to work for me. 🤔

**Comment by nosmirck** [comment]
Just did, same error.

**Comment by felangel** [comment]
Just to confirm:

1. create a directory (`mkdir tmp`)
2. create a `pubspec.yaml` in tmp (`touch pubspec.yaml`)
3. Paste the contents into the `pubspec.yaml`

```yaml
name: flutter_todos
description: A new Flutter project.

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ">=1.1.0 <2.0.0"
  equatable: ^0.2.0
  flutter_bloc: ^0.7.0
  flutter:
    sdk: flutter

dependency_overrides:
  todos_app_core:
    git:
      url: https://github.com/brianegan/flutter_architecture_samples
      path: todos_app_core
      ref: 0d047565ea5bf28c2b2cbdd7a7d9a9d14fff6945
  todos_repository_core:
    git:
      url: https://github.com/brianegan/flutter_architecture_samples
      path: todos_repository_core
      ref: 0d047565ea5bf28c2b2cbdd7a7d9a9d14fff6945
  todos_repository_simple:
    git:
      url: https://github.com/brianegan/flutter_architecture_samples
      path: todos_repository_simple
      ref: 0d047565ea5bf28c2b2cbdd7a7d9a9d14fff6945
flutter:
  uses-material-design: true
```

4. Save and run `flutter packages get`

You still get the error?
