### ISSUE TITLE
flutter_bloc for Flutter WEB

### ISSUE THREAD

**Issue by fvisticot** [felangel/bloc#281]
We try to use flutter_bloc with flutter WEB and it does not work:

Error message: flutter_bloc depends on flutter any from sdk which is forbidden, flutter_bloc is forbidden.

any idea ?

After more reading, I understand that i need to fork the flutter_bloc and make a replace "script" for plugin imports (replace import flutter to import flutter_web)

**Comment by felangel** [comment]
Hi @fvisticot 👋 
Thanks for opening an issue!

Flutter for web is still in a technical preview stage and they have forked flutter temporarily in order to ensure everything works properly before merging back into master. I would not recommend spending time to get flutter_bloc working for flutter_web because it’s not in a stable state yet. Once flutter for web stabilizes and is recommended for production use I will ensure that the library is fully compatible 👍

Hope that helps 👍

**Comment by QoLTech** [comment]
I am using this in my flutter_web project.

All that needed to be done is changing the pubspec.yaml of flutter_bloc to use flutter_web instead of flutter and changing the imports to flutter_web instead of flutter.

**Comment by felangel** [comment]
@QoLTech I will create a flutter_web branch that people can use to test with flutter_web shortly 👍

**Comment by geminiyellow** [comment]
hi @felangel , flutter/flutter#32360 merged, do you have any plan make this library work in flutter_web ?

**Comment by felangel** [comment]
@geminiyellow yes this library should work on mobile, desktop, and web 👍

Is there any problem you’re running into currently?

**Comment by geminiyellow** [comment]
hi @felangel yes, here is what i do:

```shell
> mkdir bloc_sample && cd bloc_sample
> stagehand flutter-web-preview
> flutter packages get
> webdev serve --auto refresh

[INFO] Serving `web` on http://localhost:8080
[INFO] Running build completed, took 12.6s
[INFO] Caching finalized dependency graph completed, took 159ms
[INFO] Succeeded after 12.8s with 548 outputs (3169 actions)
^C⏎        

# add  flutter_bloc: any 

> flutter packages get
> webdev serve --auto refresh

Unhandled exception:
ProcessException: ***OUT***

***ERR***
The Flutter SDK is not available.

***
  Command: /Users/dev/Documents/Source/flutter/bin/cache/dart-sdk/bin/pub deps
#0      _runPubDeps (package:webdev/src/pubspec.dart:70:5)
<asynchronous suspension>
#1      PubspecLock.read (package:webdev/src/pubspec.dart:84:11)
<asynchronous suspension>
#2      readPubspecLock (package:webdev/src/command/shared.dart:62:39)
<asynchronous suspension>
#3      ServeCommand.run (package:webdev/src/command/serve_command.dart:101:29)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:111:11)
#9      run (package:webdev/src/webdev_command_runner.dart:19:56)
#10     main (file:///Users/dev/Documents/Source/flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.0.4/bin/webdev.dart:17:22)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

```

**Comment by felangel** [comment]
@geminiyellow what version of flutter are you using? Can you please post the output of flutter doctor —verbose? Thanks!

**Comment by geminiyellow** [comment]
okey, here is it:

```shell
> flutter doctor —v
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
[✓] VS Code (version 1.33.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by felangel** [comment]
Can you try flutter upgrade —force to use latest master? I don’t think the changes are in stable.

**Comment by geminiyellow** [comment]
i did it, nothing change here.

```
> flutter upgrade —force
Upgrading Flutter from /Users/dev/Documents/Source/flutter...
Updating b593f5167..7a4c33425
 11 files changed, 488 insertions(+), 83 deletions(-)

Upgrading engine...

Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (2 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

Running "flutter packages upgrade" in native_sample...              4.5s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
[✓] VS Code (version 1.33.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by geminiyellow** [comment]
opps, sorry, you say master. sorry.

**Comment by geminiyellow** [comment]
@felangel , now i m in 

```shell
> flutter doctor —v
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.5.9-pre.234, on Mac OS X 10.14.4 18E226, locale ja-JP)
```

and , still not working. same error. 

BTW, i use it **(flutter_bloc)** in web.

**Comment by felangel** [comment]
@geminiyellow i'm taking a look right now 👍

**Comment by felangel** [comment]
@geminiyellow you can update your `pubspec.yaml` to point to a temporary flutter_web compatibility branch for `flutter_bloc`

```yaml
name: bloc_sample
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  flutter_bloc:
    git:
      url: https://github.com/felangel/bloc
      path: packages/flutter_bloc
      ref: flutter_web

dev_dependencies:
  build_runner: any
  build_web_compilers: '>=1.0.0 <2.0.0'
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
```

**Comment by geminiyellow** [comment]
hey ya, it working. thank you @felangel , will u release it later?

**Comment by axellebot** [comment]
# TLDR :
At the moment if you want to use Flutter on the web you have too replace all `flutter` package use by `flutter_web` package in all source code and library you are using.

@felangel just pushed this change on a branch for a temporary use to make it easier for you to use this library with `flutter_web`.

# Explain :

@geminiyellow this is just a hax to make `bloc` use `flutter_web` package instead of the `flutter` package.

You have to know that the flutter team that work on flutter for web have forked the official `flutter` package to use a stable version of the flutter SDK. So temporary they using this version by importing `flutter_web` package instead of `flutter` package.

When the `flutter_web` package will be release it will be merged with the `flutter` package and the `flutter_web` will no longer exists :)

**Comment by MichealReed** [comment]
@felangel I'm running into this error when trying to use the workaround you mentioned. Any tips?

```
Resolving dependencies...
Package doesn't exist (the pubspec for flutter_bloc 0.13.0 from git has version 0.17.0).
exit code 69
```

**Comment by axellebot** [comment]
> @felangel I'm running into this error when trying to use the workaround you mentioned. Any tips?
> 
> ```
> Resolving dependencies...
> Package doesn't exist (the pubspec for flutter_bloc 0.13.0 from git has version 0.17.0).
> exit code 69
> ```

Can you give us the `pubspec.yml` file please ?

**Comment by MichealReed** [comment]
@axellebot 
```

name: flutter_weather
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  http: ^0.12.0
  socket_io_client: ^0.9.1
  flutter_bloc: 
    git:
      url: https://github.com/felangel/bloc
      path: packages/flutter_bloc
      ref: flutter_web
  equatable: ^0.1.0

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
```

**Comment by axellebot** [comment]
@MichealReed  Can you add to the same post `flutter doctor` info ?

**Comment by axellebot** [comment]
It looks like the package command mixing  the `0.17.0`  version and the `flutter_web` branch version (`0.13.0`) from the cached `flutter_bloc` package ... 🤔 

Can you check all cached version of `flutter_bloc` package ?

**Comment by MichealReed** [comment]
@axellebot I've tried `flutter clean` to no avail. Any other way to delete/check cache, a bit new to flutter.

**Comment by axellebot** [comment]
All dependencies for flutter project are managed by the same software as Dart `pub`, you should be able to see all hosted libraries in this directory :
- Windows : `%APPDATA%\Pub\Cache\hosted\pub.dartlang.org` 
- Linux : `~/.pub-cache`

**Comment by MichealReed** [comment]
I checked the folders in both `/git/cache` and `/pub.dartlang.org` and deleted the older versions, but I'm still getting the same error. Should I try with a fresh project, or will that not matter?

**Comment by felangel** [comment]
@MichealReed I just tried and was not able to reproduce your issue. Can you please just try clearing your entire pub-cache?

**Comment by MichealReed** [comment]
@felangel tried clearing entire pubcache, tried [this](https://stackoverflow.com/questions/55399209/update-flutter-dependencies-in-pub-cache), tried get and upgrade. Not sure what's happening here, could there be a problem with the repo?

**Comment by felangel** [comment]
@MichealReed can you confirm the problem still happens when you create a fresh flutter project?

**Comment by MichealReed** [comment]
@felangel hitting same project on fresh project.

**Comment by felangel** [comment]
@MichealReed I’ll investigate shortly 👍

**Comment by felangel** [comment]
@MichealReed are you on [gitter](https://gitter.im/bloc_package/Lobby)? It would be much easier to debug the issue over chat/a live coding session.

**Comment by Muldec** [comment]
> @felangel I'm running into this error when trying to use the workaround you mentioned. Any tips?
> 
> ```
> Resolving dependencies...
> Package doesn't exist (the pubspec for flutter_bloc 0.13.0 from git has version 0.17.0).
> exit code 69
> ```

@MichealReed 

I had the same problem and fixed it with :

```
dependencies:
  flutter_bloc: any

dependency_overrides:
  flutter_bloc: 
    git:
      url: https://github.com/felangel/bloc
      path: packages/flutter_bloc
      ref: flutter_web
```
