### ISSUE TITLE
[bloc_test] uses out of date mocktail version

### ISSUE THREAD

**Issue by aoatmon** [felangel/bloc#2905]
**Steps To Reproduce**

- add to `pubspec.yaml`
```yaml
environment:
  sdk: '>=2.14.3 <3.0.0'
  flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  bloc_test: ^8.3.0
  mocktail: ^0.2.0
```
- run `flutter pub get`

**Expected Behavior**

everything is up to date

**Actual Behavior**

```console
Because xxxx depends on bloc_test ^8.3.0 which depends on mocktail ^0.1.1, mocktail ^0.1.1 is required.
So, because xxxx depends on mocktail ^0.2.0, version solving failed.
Running "flutter pub get" in xxxx...
pub get failed (1; So, because xxxx depends on mocktail ^0.2.0, version solving failed.)
```
