### ISSUE TITLE
fix: test timed out after 30 seconds

### ISSUE THREAD

**Issue by yeikel16** [felangel/bloc#2999]
Hello, I am contributing with @marcossevilla  and @elianmortega in the update of the new bloc API in [this open source repository](https://github.com/NoScopeDevs/bloc_samples) in example `preference_navigation`, but when updating the dependencies, two tests fail because time is running out.

**Steps To Reproduce**

1. I update the dependencies in the pubspec.yaml
```
name: preference_navigation
description: A Flutter project to show how to start an app based on a state.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  hive: ^2.0.4
  hive_preferences_repository:
    path: packages/preferences/hive_preferences_repository
  path_provider: ^2.0.2
  preferences_repository:
    path: packages/preferences/preferences_repository
  shared_preferences: ^2.0.6
  shared_preferences_repository:
    path: packages/preferences/shared_preferences_repository

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mockingjay: ^0.2.0-dev.3
  mocktail: ^0.2.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true

```

2. Remove all the `registerFallbackValue` which are no longer needed.
3. Run all the tests.
4. Fails the group `PreferenceAdded` in `prefefences_bloc_test.dart`.

**Additional Context**
However when writing the tests as normal `unitTest` they pass without any problem and with the `blocTest` they throw a `TimeoutException`.
`TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
dart:isolate  _RawReceivePortImpl._handleMessage`

Example:
```
test('test 1', () {
        when(preferencesRepository.getKeys).thenReturn(
          [mockSavedPreferences.keys.first, mockPreferences.keys.first],
        );
        when(() => preferencesRepository.saveValue(any(), any()))
            .thenAnswer((_) => Future<void>.value());
        when(
          () => preferencesRepository.getValue(mockSavedPreferences.keys.first),
        ).thenReturn(mockSavedPreferences.values.first);
        when(
          () => preferencesRepository.getValue(mockPreferences.keys.first),
        ).thenReturn(mockPreferences.values.first);

        final bloc = PreferencesBloc(repository: preferencesRepository)
          ..add(const PreferenceAdded(mockPreferences));

        expect(
          bloc.stream,
          emitsInOrder(<PreferencesState>[
            const PreferencesLoading(),
            PreferencesLoaded(
              <String, dynamic>{
                mockSavedPreferences.keys.first:
                    mockSavedPreferences.values.first,
                mockPreferences.keys.first: mockPreferences.values.first,
              },
            ),
          ]),
        );
      });

      test('test 2', () {
        when(preferencesRepository.getKeys).thenReturn(
          [mockSavedPreferences.keys.first, mockPreferences.keys.first],
        );
        when(() => preferencesRepository.saveValue(any(), any()))
            .thenThrow(Exception());
        when(
          () => preferencesRepository.getValue(mockSavedPreferences.keys.first),
        ).thenReturn(mockSavedPreferences.values.first);
        when(
          () => preferencesRepository.getValue(mockPreferences.keys.first),
        ).thenReturn(mockPreferences.values.first);

        final bloc = PreferencesBloc(repository: preferencesRepository)
          ..add(const PreferenceAdded(mockPreferences));

        expect(
          bloc.stream,
          emitsInOrder(const <PreferencesState>[
            PreferencesLoading(),
            PreferencesError(),
          ]),
        );
      });
```
