### ISSUE TITLE
fix: Impossible to Install `bloc_test`, Version Solving Failed

### ISSUE THREAD

**Issue by erayerdin** [felangel/bloc#3110]
**Description**
It is impossible to install `bloc_test`, it fails with the latest stable version of Flutter.

**Steps To Reproduce**

1. Create new Flutter project.
2. Add `bloc_test` to `dev_dependencies`. You can add the latest 9.0.2 version or even do `any` to let the pub deal with latest compatible version.
3. Fail.

**Expected Behavior**
For it to install without any problem.

**Additional Context**

`pubspec.yaml` file:

```yaml
name: myapp
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc: ^8.0.2
  cupertino_icons: ^1.0.2
  file_picker: ^4.3.0
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_loggy: ^2.0.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  json_serializable: ^6.1.3
  loggy: ^2.0.1
  path: ^1.8.0

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

Fails with saying (if version is 9.0.2):

```plain
[myapp] flutter pub get
Running "flutter pub get" in myapp...                      
Because test >=1.16.0-nullsafety.19 <1.16.6 depends on test_api 0.2.19 and test >=1.16.6 <1.17.10 depends on analyzer ^1.0.0, test >=1.16.0-nullsafety.19 <1.17.10 requires test_api 0.2.19 or analyzer ^1.0.0.
And because test >=1.17.10 <1.20.0 depends on analyzer >=1.0.0 <3.0.0 and test >=1.20.0 depends on test_api 0.4.9, test >=1.16.0-nullsafety.19 requires test_api 0.2.19 or 0.4.9 or analyzer >=1.0.0 <3.0.0.
Because no versions of freezed match >1.1.1 <2.0.0 and freezed 1.1.1 depends on analyzer ^3.0.0, freezed ^1.1.1 requires analyzer ^3.0.0.
Thus, if freezed ^1.1.1 and test >=1.16.0-nullsafety.19 then test_api 0.2.19 or 0.4.9.
And because every version of flutter_test from sdk depends on test_api 0.4.3, one of freezed ^1.1.1 or test >=1.16.0-nullsafety.19 or flutter_test from sdk must be false.
And because myapp depends on bloc_test ^9.0.2 which depends on test ^1.16.0, freezed ^1.1.1 is incompatible with flutter_test from sdk.
So, because myapp depends on both flutter_test from sdk and freezed ^1.1.1, version solving failed.
pub get failed (1; So, because myapp depends on both flutter_test from sdk and freezed ^1.1.1, version solving failed.)
exit code 1
```

Fails with saying if version is set to `any`:

```plain
[myapp] flutter pub get
Running "flutter pub get" in myapp...                      
    Because bloc_test >=3.0.0-dev.1 <3.0.0 depends on bloc ^3.0.0-dev.1 and bloc_test >=5.0.0-dev.1 <5.0.0-dev.2 depends on bloc ^4.0.0-dev.1, bloc_test >=3.0.0-dev.1 <3.0.0 or >=5.0.0-dev.1 <5.0.0-dev.2 requires bloc ^3.0.0-dev.1 or ^4.0.0-dev.1.
    And because bloc_test >=5.0.0-dev.2 <5.0.0-dev.3 depends on bloc ^4.0.0-dev.2, bloc_test >=3.0.0-dev.1 <3.0.0 or >=5.0.0-dev.1 <5.0.0-dev.3 requires bloc ^3.0.0-dev.1 or >=4.0.0-dev.1 <5.0.0.
    And because bloc_test >=5.0.0-dev.3 <5.0.0-dev.4 depends on bloc ^4.0.0-dev.3 and bloc_test >=5.0.0-dev.4 <5.0.0 depends on bloc ^4.0.0-dev.4, bloc_test >=3.0.0-dev.1 <3.0.0 or >=5.0.0-dev.1 <5.0.0 requires bloc ^3.0.0-dev.1 or >=4.0.0-dev.1 <5.0.0.
    And because bloc_test >=6.0.0-dev.1 <6.0.0-dev.2 depends on bloc ^5.0.0-dev.6 and bloc_test >=6.0.0-dev.2 <6.0.0-dev.3 depends on bloc ^5.0.0-dev.7, bloc_test >=3.0.0-dev.1 <3.0.0 or >=5.0.0-dev.1 <5.0.0 or >=6.0.0-dev.1 <6.0.0-dev.3 requires bloc ^3.0.0-dev.1 or >=4.0.0-dev.1 <5.0.0 or >=5.0.0-dev.6 <6.0.0.
    And because bloc_test >=6.0.0-dev.3 <6.0.0-dev.4 depends on bloc ^5.0.0-dev.10 and bloc_test >=6.0.0-dev.4 <6.0.0 depends on bloc ^5.0.0-dev.11, bloc_test >=3.0.0-dev.1 <3.0.0 or >=5.0.0-dev.1 <5.0.0 or >=6.0.0-dev.1 <6.0.0 requires bloc ^3.0.0-dev.1 or >=4.0.0-dev.1 <5.0.0 or >=5.0.0-dev.6 <6.0.0.
    And because bloc_test >=7.0.0-dev.1 <7.0.0 depends on bloc ^6.0.0-dev.1 and bloc_test >=8.0.0-nullsafety.0 <8.0.0-nullsafety.2 depends on test ^1.16.0, bloc_test >=3.0.0-dev.1 <3.0.0 or >=5.0.0-dev.1 <5.0.0 or >=6.0.0-dev.1 <6.0.0 or >=7.0.0-dev.1 <7.0.0 or >=8.0.0-nullsafety.0 <8.0.0-nullsafety.2 requires bloc ^3.0.0-dev.1 or >=4.0.0-dev.1 <5.0.0 or >=5.0.0-dev.6 <6.0.0 or ^6.0.0-dev.1 or test ^1.16.0.
    And because bloc_test >=8.0.0-nullsafety.2 <8.0.0-nullsafety.5 depends on test_api ^0.2.19 and bloc_test <1.0.0 depends on bloc ^0.16.0, bloc_test <1.0.0-∞ or >=3.0.0-dev.1 <3.0.0 or >=5.0.0-dev.1 <5.0.0 or >=6.0.0-dev.1 <6.0.0 or >=7.0.0-dev.1 <7.0.0 or >=8.0.0-nullsafety.0 <8.0.0-nullsafety.5 requires bloc ^0.16.0 or ^3.0.0-dev.1 or >=4.0.0-dev.1 <5.0.0 or >=5.0.0-dev.6 <6.0.0 or ^6.0.0-dev.1 or test ^1.16.0 or test_api ^0.2.19.
    And because bloc_test ^1.0.0 depends on bloc ^1.0.0 and bloc_test >=2.0.0 <3.0.0-dev.1 depends on bloc ^2.0.0, bloc_test <3.0.0-∞ or >=5.0.0-dev.1 <5.0.0 or >=6.0.0-dev.1 <6.0.0 or >=7.0.0-dev.1 <7.0.0 or >=8.0.0-nullsafety.0 <8.0.0-nullsafety.5 requires bloc ^0.16.0 or ^1.0.0 or ^2.0.0 or ^3.0.0-dev.1 or >=4.0.0-dev.1 <5.0.0 or >=5.0.0-dev.6 <6.0.0 or ^6.0.0-dev.1 or test ^1.16.0 or test_api ^0.2.19.
    And because bloc_test >=3.0.0 <5.0.0-dev.1 depends on bloc ^3.0.0 and bloc_test >=5.0.0 <6.0.0-dev.1 depends on bloc ^4.0.0, bloc_test <6.0.0-∞ or >=7.0.0-dev.1 <7.0.0 or >=8.0.0-nullsafety.0 <8.0.0-nullsafety.5 requires bloc ^0.16.0 or ^1.0.0 or ^2.0.0 or >=3.0.0-dev.1 <4.0.0 or >=4.0.0-dev.1 <5.0.0 or >=5.0.0-dev.6 <6.0.0 or ^6.0.0-dev.1 or test ^1.16.0 or test_api ^0.2.19.
    And because bloc_test >=6.0.0 <6.0.1 depends on bloc ^5.0.0 and bloc_test >=6.0.1 <7.0.0-dev.1 depends on bloc ^5.0.1, bloc_test <7.0.0-∞ or >=8.0.0-nullsafety.0 <8.0.0-nullsafety.5 requires bloc ^0.16.0 or ^1.0.0 or ^2.0.0 or >=3.0.0-dev.1 <4.0.0 or >=4.0.0-dev.1 <5.0.0 or >=5.0.0-dev.6 <6.0.0 or ^6.0.0-dev.1 or test ^1.16.0 or test_api ^0.2.19.
(1) So, because bloc_test >=7.0.0 <8.0.0-nullsafety.0 depends on bloc ^6.0.0 and bloc_test >=8.0.0-nullsafety.5 depends on test ^1.16.0, every version of bloc_test requires bloc ^0.16.0 or ^1.0.0 or ^2.0.0 or >=3.0.0-dev.1 <4.0.0 or >=4.0.0-dev.1 <5.0.0 or >=5.0.0-dev.6 <6.0.0 or >=6.0.0-dev.1 <7.0.0 or test ^1.16.0 or test_api ^0.2.19.

    Because test >=1.16.0-nullsafety.19 <1.16.6 depends on test_api 0.2.19 and test >=1.16.6 <1.17.10 depends on analyzer ^1.0.0, test >=1.16.0-nullsafety.19 <1.17.10 requires test_api 0.2.19 or analyzer ^1.0.0.
    And because test >=1.17.10 <1.20.0 depends on analyzer >=1.0.0 <3.0.0 and test >=1.20.0 depends on test_api 0.4.9, test >=1.16.0-nullsafety.19 requires test_api 0.2.19 or 0.4.9 or analyzer >=1.0.0 <3.0.0.
    And because every version of bloc_test requires bloc ^0.16.0 or ^1.0.0 or ^2.0.0 or >=3.0.0-dev.1 <4.0.0 or >=4.0.0-dev.1 <5.0.0 or >=5.0.0-dev.6 <6.0.0 or >=6.0.0-dev.1 <7.0.0 or test ^1.16.0 or test_api ^0.2.19 (1), every version of bloc_test requires bloc ^0.16.0 or ^1.0.0 or ^2.0.0 or >=3.0.0-dev.1 <4.0.0 or >=4.0.0-dev.1 <5.0.0 or >=5.0.0-dev.6 <6.0.0 or >=6.0.0-dev.1 <7.0.0 or test_api ^0.2.19 or 0.4.9 or analyzer >=1.0.0 <3.0.0.
    Because no versions of freezed match >1.1.1 <2.0.0 and freezed 1.1.1 depends on analyzer ^3.0.0, freezed ^1.1.1 requires analyzer ^3.0.0.
    Thus, if freezed ^1.1.1 and bloc_test any then bloc ^0.16.0 or ^1.0.0 or ^2.0.0 or >=3.0.0-dev.1 <4.0.0 or >=4.0.0-dev.1 <5.0.0 or >=5.0.0-dev.6 <6.0.0 or >=6.0.0-dev.1 <7.0.0 or test_api ^0.2.19 or 0.4.9.
    And because every version of flutter_test from sdk depends on test_api 0.4.3, if freezed ^1.1.1 and bloc_test any and flutter_test from sdk then bloc ^0.16.0 or ^1.0.0 or ^2.0.0 or >=3.0.0-dev.1 <4.0.0 or >=4.0.0-dev.1 <5.0.0 or >=5.0.0-dev.6 <6.0.0 or >=6.0.0-dev.1 <7.0.0.
    And because myapp depends on both bloc ^8.0.2 and bloc_test any, freezed ^1.1.1 is incompatible with flutter_test from sdk.
    So, because myapp depends on both flutter_test from sdk and freezed ^1.1.1, version solving failed.
pub get failed (1;     So, because myapp depends on both flutter_test from sdk and freezed ^1.1.1, version solving failed.)
exit code 1
```

`flutter --version` information:

```plain
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (3 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

Installed on KDE Neon 5.23 (based on Ubuntu 20.04) with Snap.

**Comment by felangel** [comment]
Hi @erayerdin 👋 
Thanks for opening an issue!

It looks like the issue is caused by the fact that `package:freezed` depends on `analyzer: ^3.0.0` which is incompatible with `package:test` and `flutter_test` on the current stable version of flutter:

```yaml
name: myapp
description: A new Flutter project.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  analyzer: ^3.0.0
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
```

This appears to have been changed in freezed v1.1.1 so you can use freezed v1.1.0 and everything should work as expected:


```yaml
name: myapp
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  cupertino_icons: ^1.0.2
  file_picker: ^4.3.0
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_loggy: ^2.0.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  json_serializable: ^6.1.3
  loggy: ^2.0.1
  path: ^1.8.0

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ">=1.0.0 <1.1.1"

flutter:
  uses-material-design: true
```

Let me know if that helps 👍
