### ISSUE TITLE
feat: check outdated version using the pubspec.lock file

### ISSUE THREAD

**Issue by fabianMendez** [felangel/bloc#3131]
**Description**

Currently the vscode extension shows a warning when the packages version is below `8.0.1`, however one could have the following inside `pubspec.yaml` and still be using the `8.0.1` version:
```yaml
dependencies:
  bloc: ^8.0.0
```

**Desired Solution**

I think it's more reliable to load the currently used version from the `pubspec.lock` file:
```yaml
packages:
  bloc:
    dependency: "direct main"
    description:
      name: bloc
      url: "https://pub.dartlang.org"
    source: hosted
    version: "8.0.2"
```

**Alternatives Considered**

Manually updating the `pubspec.yaml` file so that the warning disappears.

**Additional Context**

![image](https://user-images.githubusercontent.com/32204060/148984448-9d78efb6-3947-44cf-8f66-924299290a3f.png)
