### ISSUE TITLE
Package doesn't exists when using flutter_bloc for flutter_web

### ISSUE THREAD

**Issue by Muldec** [felangel/bloc#413]
Hi !

**Describe the bug**

When I try to use flutter_bloc in a flutter for web project, I get the following message when updating pubspec:

```
[hello_world] pub get
Resolving dependencies...
Package doesn't exist (the pubspec for flutter_bloc 0.19.0 from git has version 0.19.1).
exit code 69
```

**To Reproduce**

1. Create a new Flutter for web project
2. Update pubspec.yaml with
```
dependencies:
  flutter_bloc:
    git:
      url: https://github.com/felangel/bloc
      path: packages/flutter_bloc
      ref: flutter_web
``` 
3. Save file and run `pub get`

Here is my full pubspec file:

```
name: hello_world
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  flutter_bloc:
    git:
      url: https://github.com/felangel/bloc
      path: packages/flutter_bloc
      ref: flutter_web

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
```

I tried the following with no effects:
* clearing the pub cache
* repairing the pub cache
* switching flutter channel from beta to master
