### ISSUE TITLE
upgrade v2.0.1 failed

### ISSUE THREAD

**Issue by lvyandev** [felangel/bloc#683]
```
Because xxx depends on flutter_bloc ^2.0.1 which doesn't match any versions, version solving failed.
pub get failed (1; Because xxx depends on flutter_bloc ^2.0.1 which doesn't match any versions, version solving failed.)
```
I am getting this error when upgrading to v2.0.1.
problem might be caused by pub mirror site for China.
```
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
```
related issues I found
#https://github.com/flutter/flutter/issues/20809#issuecomment-416147950

**Comment by felangel** [comment]
Hi @lvyandev 👋 
Thanks for opening an issue!

I think as you mentioned the problem is due to the pub mirror not having a reference to the latest version of flutter_bloc.

You can temporarily point to the git url if you'd like

```yaml
flutter_bloc:
    git:
      url: https://github.com/felangel/bloc
      path: packages/flutter_bloc
      ref: 4f0a73addd95f207860421e4afc5d7f108a98da5
```

Hope that helps 👍
